name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.7830123f-2271-4fab-94a2-b1c6b2e2e90b}}
          heroku_app_name: "dguaudit" #Must be unique in Heroku
          heroku_email: "s.a.pavlov@mail.ru"